"""Estimate ice porosity with Bruggeman effective-medium theory.

This workflow extracts drift-corrected THz optical constants, uses a fixed
solid-ice density of 0.917 g/cm^3, inverts the Bruggeman model, and
compares optical porosity with gravimetric porosity. Uncertainties are standard
uncertainties. The residual uncertainty includes the covariance generated by
using the same thickness input in both porosity estimates.
"""

from __future__ import annotations

import argparse
import csv
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, List, Sequence, Tuple

import matplotlib.pyplot as plt
import numpy as np
from pydotthz import DotthzFile

from plot_outputs import save_figure_outputs

from analyze_measurement_campaigns import (
    DEFAULT_CONFIG_DIR,
    DEFAULT_OUTPUT_DIR,
    EPS_VACUUM,
    SOLID_ICE_DENSITY_G_CM3,
    CampaignConfig,
    collect_config_paths,
    compute_density,
    compute_refractive_index_error,
    get_thz_files,
    get_refraction_index,
    load_campaign_config,
    make_unique_legend,
    read_trace_cached,
    tao_ice_refractive_index_at_1thz,
)

EMT_MODELS = ("bruggeman",)


@dataclass
class OpticalMeasurement:
    """Optical, gravimetric, and uncertainty data for one analyzed sample.

    ``true_porosity_thickness_component`` is a signed one-standard-uncertainty
    contribution retained specifically for covariance propagation.
    """
    campaign_id: str
    label: str
    measurement_id: str
    plot_color: str
    density_g_cm3: float
    density_err_g_cm3: float
    is_solid_measurement: bool
    true_porosity: float
    true_porosity_err: float
    true_porosity_thickness_component: float
    thickness_mm: float
    thickness_err_mm: float
    frequencies_thz: np.ndarray
    complex_refractive_index: np.ndarray
    refractive_index_at_1thz: float
    refractive_index_err: float
    complex_refractive_index_at_1thz: complex


@dataclass
class PorosityEstimate:
    """EMT porosity result and its comparison with gravimetric porosity.

    ``porosity_error`` is estimated minus gravimetric porosity;
    ``porosity_error_err`` is its propagated standard uncertainty and
    ``porosity_covariance`` has units of porosity squared.
    """
    model: str
    estimated_porosity: float
    estimated_porosity_err: float
    porosity_error: float
    porosity_error_err: float
    porosity_covariance: float


def read_embedded_ref_trace(path: Path) -> Tuple[np.ndarray, np.ndarray]:
    """Read, align, and average embedded ``Ref`` traces from THz files."""
    time_axis: np.ndarray | None = None
    traces: List[np.ndarray] = []

    for thz_file in get_thz_files(path):
        with DotthzFile(thz_file) as handle:
            ref_dataset = handle["Single Pixel 0"].datasets.get("Ref")
            if ref_dataset is None:
                raise KeyError(f"No embedded Ref dataset in {thz_file}")
            ref_trace = ref_dataset[:]
            t = np.asarray(ref_trace[:, 0])
            p = np.asarray(ref_trace[:, 1])

        mask = (t > 1860) & (t < 1960)
        t = t[mask]
        p = p[mask]

        if time_axis is None:
            time_axis = t
        elif t.shape != time_axis.shape or not np.allclose(t, time_axis):
            p = np.interp(time_axis, t, p)

        traces.append(p)

    if time_axis is None:
        raise RuntimeError(f"No embedded Ref traces found in {path}")

    return time_axis, np.mean(np.vstack(traces), axis=0)


def read_embedded_ref_trace_cached(
        path: Path,
        cache: Dict[Path, Tuple[np.ndarray, np.ndarray]],
) -> Tuple[np.ndarray, np.ndarray]:
    """Return an averaged embedded reference trace from a caller-owned cache."""
    if path not in cache:
        cache[path] = read_embedded_ref_trace(path)
    return cache[path]


def estimate_time_shift(reference_time: np.ndarray, reference_trace: np.ndarray, shifted_trace: np.ndarray) -> float:
    """Estimate an integer-sample time shift by full cross-correlation.

    Returns:
        Signed shift in picoseconds. The sign follows the lag convention of
        ``numpy.correlate(reference_trace, shifted_trace)``.
    """
    centered_reference = reference_trace - np.mean(reference_trace)
    centered_shifted = shifted_trace - np.mean(shifted_trace)
    correlation = np.correlate(centered_reference, centered_shifted, mode="full")
    lags = np.arange(-len(centered_shifted) + 1, len(centered_reference))
    best_lag = lags[int(np.argmax(correlation))]
    sample_spacing_ps = float(np.mean(np.diff(reference_time)))
    return best_lag * sample_spacing_ps


def shift_trace(time_axis: np.ndarray, trace: np.ndarray, shift_ps: float) -> np.ndarray:
    """Shift a trace by interpolation and zero-fill samples outside its span."""
    shifted = np.interp(
        time_axis + shift_ps,
        time_axis,
        trace,
        left=np.nan,
        right=np.nan,
    )
    invalid = np.isnan(shifted)
    if np.any(invalid):
        shifted[invalid] = 0.0
    return shifted


def compensate_sample_trace_from_embedded_refs(
        measurement_path: Path,
        reference_path: Path,
        sample_time: np.ndarray,
        sample_trace: np.ndarray,
        embedded_ref_cache: Dict[Path, Tuple[np.ndarray, np.ndarray]],
) -> np.ndarray:
    """Align a sample trace using its and the baseline's embedded references.

    If either acquisition lacks an embedded ``Ref`` dataset, the input sample
    trace is returned unchanged. This fallback keeps legacy acquisitions usable.
    """
    try:
        reference_ref_t, reference_ref_p = read_embedded_ref_trace_cached(reference_path, embedded_ref_cache)
        measurement_ref_t, measurement_ref_p = read_embedded_ref_trace_cached(measurement_path, embedded_ref_cache)
    except (KeyError, RuntimeError):
        return sample_trace

    if (
            measurement_ref_t.shape != reference_ref_t.shape
            or not np.allclose(measurement_ref_t, reference_ref_t)
    ):
        measurement_ref_p = np.interp(reference_ref_t, measurement_ref_t, measurement_ref_p)
        measurement_ref_t = reference_ref_t

    # every measurement contains a second reference measurement in clear path. this is compared with the solid ice
    # measurement clear path reference to compensate for any instrument temporal drift
    reference_shift_ps = estimate_time_shift(
        reference_time=reference_ref_t,
        reference_trace=reference_ref_p,
        shifted_trace=measurement_ref_p,
    )
    applied_sample_shift_ps = -reference_shift_ps
    return shift_trace(sample_time, sample_trace, applied_sample_shift_ps)


def bruggeman_vi(epsilon_eff: complex, epsilon_ice: complex) -> complex:
    """Invert symmetric Bruggeman EMT for the ice volume fraction."""
    lhs = (EPS_VACUUM - epsilon_eff) / (EPS_VACUUM + 2 * epsilon_eff)
    rhs = (epsilon_ice - epsilon_eff) / (epsilon_ice + 2 * epsilon_eff)
    return lhs / (lhs - rhs)


def bruggeman_eps(volume_fraction_ice: np.ndarray, eps_host: complex, eps_ice: complex) -> np.ndarray:
    """Evaluate effective permittivity on the physical Bruggeman branch."""
    b_term = 3 * volume_fraction_ice * (eps_ice - eps_host) + 2 * eps_host - eps_ice
    return (b_term + np.sqrt(b_term ** 2 + 8 * eps_host * eps_ice)) / 4


def emt_model_label(model: str) -> str:
    """Return a display label for an internal EMT model key."""
    if model == "bruggeman":
        return "Bruggeman"
    raise ValueError(f"Unsupported EMT model: {model}")


def invert_volume_fraction(model: str, epsilon_eff: complex, epsilon_ice: complex) -> float:
    """Invert an EMT relation and clip its real ice fraction to ``[0, 1]``."""
    if model != "bruggeman":
        raise ValueError(f"Unsupported EMT model: {model}")
    value = bruggeman_vi(epsilon_eff, epsilon_ice)
    return float(np.clip(np.real(value), 0.0, 1.0))


def forward_emt_curve(model: str, solid_ice_density_g_cm3: float) -> Tuple[
    np.ndarray, np.ndarray]:
    """Return a bulk-density/refractive-index EMT curve at 1 THz.

    Solid-ice permittivity is obtained from the Tao et al. refractive index at
    exactly 1 THz; the supplied density sets the ice-volume-fraction scale.
    """
    density_axis = np.linspace(0.0, solid_ice_density_g_cm3, 300)
    volume_fraction_ice = np.clip(density_axis / solid_ice_density_g_cm3, 0.0, 1.0)
    eps_ice = tao_ice_refractive_index_at_1thz() ** 2

    if model != "bruggeman":
        raise ValueError(f"Unsupported EMT model: {model}")
    eps_eff = bruggeman_eps(volume_fraction_ice, EPS_VACUUM, eps_ice)

    return density_axis, np.real(np.sqrt(eps_eff))


def parse_args() -> argparse.Namespace:
    """Parse command-line options for the porosity workflow."""
    parser = argparse.ArgumentParser(
        description=(
            "Analyze THz-TDS porosity using the Bruggeman effective-medium model."
        )
    )
    parser.add_argument(
        "--config-dir",
        type=Path,
        default=DEFAULT_CONFIG_DIR,
        help="Directory containing campaign JSON config files.",
    )
    parser.add_argument(
        "--config",
        action="append",
        default=[],
        help="Specific config file(s) to analyze. Defaults to all JSON files in --config-dir.",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=DEFAULT_OUTPUT_DIR,
        help="Directory for plot and CSV outputs.",
    )
    parser.add_argument(
        "--show",
        action="store_true",
        help="Show plots interactively in addition to saving them.",
    )
    return parser.parse_args()


def collect_measurements(campaigns: Sequence[CampaignConfig]) -> List[OpticalMeasurement]:
    """Extract drift-corrected optical and gravimetric data for all campaigns."""
    trace_cache: Dict[Path, Tuple[np.ndarray, np.ndarray, int]] = {}
    embedded_ref_cache: Dict[Path, Tuple[np.ndarray, np.ndarray]] = {}
    results: List[OpticalMeasurement] = []

    for campaign in campaigns:
        settings = campaign.analysis
        fit_band_min, fit_band_max = settings.fit_band_thz

        for measurement in campaign.measurements:
            if measurement.ignore:
                continue

            sample_t, sample_p, _ = read_trace_cached(measurement.path, trace_cache)
            sample_p = compensate_sample_trace_from_embedded_refs(
                measurement_path=measurement.path,
                reference_path=measurement.reference_path,
                sample_time=sample_t,
                sample_trace=sample_p,
                embedded_ref_cache=embedded_ref_cache,
            )
            reference_t, reference_p, _ = read_trace_cached(measurement.reference_path, trace_cache)
            freqs, refractive_index, complex_refractive_index = get_refraction_index(
                sample_t,
                sample_p,
                reference_t,
                reference_p,
                window_half_width=settings.window_half_width,
                win_func=settings.window_function,
                min_frequency=settings.min_frequency_thz,
                max_frequency=settings.max_frequency_thz,
                d_mm=measurement.thickness_mm,
            )

            density_g_cm3, density_err_g_cm3 = compute_density(
                measurement.mass_kg,
                measurement.thickness_mm,
                settings,
                mass_err_kg=measurement.mass_err_kg,
                thickness_err_mm=measurement.thickness_err_mm,
            )
            fit_mask = (freqs > fit_band_min) & (freqs < fit_band_max)
            refractive_index_at_1thz = float(np.nanmean(refractive_index[fit_mask]))
            complex_refractive_index_at_1thz = complex(np.nanmean(complex_refractive_index[fit_mask]))
            refractive_index_err = compute_refractive_index_error(
                refractive_index_at_1thz,
                measurement.thickness_mm,
                measurement.thickness_err_mm,
            )

            results.append(
                OpticalMeasurement(
                    campaign_id=campaign.campaign_id,
                    label=measurement.label,
                    measurement_id=measurement.measurement_id,
                    plot_color=campaign.plot_color,
                    density_g_cm3=density_g_cm3,
                    density_err_g_cm3=density_err_g_cm3,
                    is_solid_measurement=measurement.label.upper() == "SOLID",
                    true_porosity=float("nan"),
                    true_porosity_err=float("nan"),
                    true_porosity_thickness_component=float("nan"),
                    thickness_mm=measurement.thickness_mm,
                    thickness_err_mm=measurement.thickness_err_mm,
                    frequencies_thz=freqs,
                    complex_refractive_index=complex_refractive_index,
                    refractive_index_at_1thz=refractive_index_at_1thz,
                    refractive_index_err=refractive_index_err,
                    complex_refractive_index_at_1thz=complex_refractive_index_at_1thz,
                )
            )

    return results


def assign_gravimetric_porosity(
        measurements: Sequence[OpticalMeasurement],
        solid_ice_density_g_cm3: float = SOLID_ICE_DENSITY_G_CM3,
) -> None:
    """Assign gravimetric porosity using a fixed solid-ice density.

    Porosity is ``1 - bulk_density / solid_ice_density``. The supplied solid
    density is treated as exact, so porosity uncertainty is the sample-density
    uncertainty divided by the solid density. The signed thickness contribution
    is stored separately for the later optical/gravimetric covariance.
    """
    if solid_ice_density_g_cm3 <= 0:
        raise ValueError("Solid-ice density must be positive.")

    for measurement in measurements:
        measurement.true_porosity = (
                1.0 - measurement.density_g_cm3 / solid_ice_density_g_cm3
        )
        measurement.true_porosity_err = (
                measurement.density_err_g_cm3 / solid_ice_density_g_cm3
        )
        relative_thickness_err = measurement.thickness_err_mm / measurement.thickness_mm
        measurement.true_porosity_thickness_component = (
                measurement.density_g_cm3
                / solid_ice_density_g_cm3
                * relative_thickness_err
        )


def estimate_porosity(
        measurement: OpticalMeasurement,
        model: str,
        epsilon_ice: complex,
) -> PorosityEstimate:
    """Invert EMT and propagate thickness uncertainty into porosity residuals.

    The EMT uncertainty is evaluated by a central finite difference in the real
    refractive index. Residual variance is
    ``u_emt**2 + u_grav**2 - 2 * covariance``. The covariance is the product of
    the signed EMT and gravimetric one-sigma thickness contributions, equivalent
    to treating their shared thickness component as perfectly correlated.
    """
    epsilon_eff = measurement.complex_refractive_index_at_1thz ** 2
    volume_fraction_ice = invert_volume_fraction(model, epsilon_eff, epsilon_ice)
    estimated_porosity = 1.0 - volume_fraction_ice

    n_lower = complex(
        measurement.refractive_index_at_1thz - measurement.refractive_index_err,
        measurement.complex_refractive_index_at_1thz.imag,
    )
    n_upper = complex(
        measurement.refractive_index_at_1thz + measurement.refractive_index_err,
        measurement.complex_refractive_index_at_1thz.imag,
    )
    porosity_lower = 1.0 - invert_volume_fraction(model, n_lower ** 2, epsilon_ice)
    porosity_upper = 1.0 - invert_volume_fraction(model, n_upper ** 2, epsilon_ice)
    estimated_porosity_thickness_component = 0.5 * (porosity_lower - porosity_upper)
    estimated_porosity_err = abs(estimated_porosity_thickness_component)

    porosity_covariance = (
            estimated_porosity_thickness_component
            * measurement.true_porosity_thickness_component
    )
    porosity_error_variance = (
            estimated_porosity_err ** 2
            + measurement.true_porosity_err ** 2
            - 2 * porosity_covariance
    )
    porosity_error_err = float(np.sqrt(max(porosity_error_variance, 0.0)))

    return PorosityEstimate(
        model=model,
        estimated_porosity=estimated_porosity,
        estimated_porosity_err=estimated_porosity_err,
        porosity_error=estimated_porosity - measurement.true_porosity,
        porosity_error_err=porosity_error_err,
        porosity_covariance=porosity_covariance,
    )


def plot_summary_figure(
        measurements: Sequence[OpticalMeasurement],
        solid_ice_density_g_cm3: float,
        bruggeman_estimates: Sequence[PorosityEstimate],
        output_stem: Path,
) -> plt.Figure:
    """Plot the forward EMT relation and covariance-aware porosity residuals."""
    fig, axes = plt.subplots(ncols=2, figsize=(13, 5), constrained_layout=True)
    ax_forward, ax_residual = axes
    for measurement in measurements:
        ax_forward.errorbar(
            measurement.density_g_cm3,
            measurement.refractive_index_at_1thz,
            xerr=measurement.density_err_g_cm3,
            yerr=measurement.refractive_index_err,
            fmt="o",
            color=measurement.plot_color,
            ecolor="black",
            markersize=5,
            capsize=2,
            markeredgecolor="black",
            markeredgewidth=0.5,
            label=measurement.campaign_id,
        )

    density_axis, refractive_index_curve = forward_emt_curve(
        "bruggeman",
        solid_ice_density_g_cm3,
    )
    ax_forward.plot(
        density_axis,
        refractive_index_curve,
        linewidth=2.0,
        color="black",
        linestyle="--",
        label="Bruggeman EMT",
    )
    ax_forward.set_xlabel(r"Ice density [g/cm$^3$]")
    ax_forward.set_ylabel("Refractive index @ 1 THz [-]")
    ax_forward.set_title("a) Refractive Index")
    make_unique_legend(ax_forward)

    ax_residual.axhline(0.0, color="black", linewidth=1.0)
    for measurement, estimate in zip(measurements, bruggeman_estimates):
        ax_residual.errorbar(
            measurement.true_porosity,
            estimate.porosity_error,
            xerr=measurement.true_porosity_err,
            yerr=estimate.porosity_error_err,
            fmt="o",
            color=measurement.plot_color,
            ecolor="black",
            markersize=5,
            capsize=2,
            markeredgecolor="black",
            markeredgewidth=0.5,
            label=measurement.campaign_id,
        )
    ax_residual.set_xlabel("True porosity [-]")
    ax_residual.set_ylabel("Estimated porosity - true porosity [-]")
    ax_residual.set_title("b) Bruggeman Residuals")
    make_unique_legend(ax_residual)

    save_figure_outputs(fig, output_stem)
    return fig


def write_measurement_summary(
        measurements: Sequence[OpticalMeasurement],
        estimates_by_model: Dict[str, List[PorosityEstimate]],
        output_path: Path,
) -> None:
    """Write per-measurement density, porosity, residual, and covariance data."""
    with output_path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.writer(handle)
        writer.writerow(
            [
                "campaign_id",
                "measurement_id",
                "label",
                "density_g_cm3",
                "density_err_g_cm3",
                "true_porosity",
                "true_porosity_err",
                "refractive_index_at_1thz",
                "refractive_index_err",
                "bruggeman_porosity",
                "bruggeman_porosity_err",
                "bruggeman_porosity_error",
                "bruggeman_porosity_error_err",
                "bruggeman_porosity_covariance",
            ]
        )
        for index, measurement in enumerate(measurements):
            writer.writerow(
                [
                    measurement.campaign_id,
                    measurement.measurement_id,
                    measurement.label,
                    measurement.density_g_cm3,
                    measurement.density_err_g_cm3,
                    measurement.true_porosity,
                    measurement.true_porosity_err,
                    measurement.refractive_index_at_1thz,
                    measurement.refractive_index_err,
                    estimates_by_model["bruggeman"][index].estimated_porosity,
                    estimates_by_model["bruggeman"][index].estimated_porosity_err,
                    estimates_by_model["bruggeman"][index].porosity_error,
                    estimates_by_model["bruggeman"][index].porosity_error_err,
                    estimates_by_model["bruggeman"][index].porosity_covariance,
                ]
            )


def write_model_metrics(
        estimates_by_model: Dict[str, List[PorosityEstimate]],
        output_path: Path,
) -> None:
    """Write aggregate signed and absolute residual metrics for each model."""
    with output_path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.writer(handle)
        writer.writerow(["model", "mae", "rmse", "bias", "max_abs_error"])
        for model in EMT_MODELS:
            errors = np.array([estimate.porosity_error for estimate in estimates_by_model[model]], dtype=float)
            writer.writerow(
                [
                    emt_model_label(model),
                    float(np.mean(np.abs(errors))),
                    float(np.sqrt(np.mean(errors ** 2))),
                    float(np.mean(errors)),
                    float(np.max(np.abs(errors))),
                ]
            )


def residual_performance(errors: Sequence[float]) -> Dict[str, float]:
    """Return empirical porosity accuracy metrics for signed residuals."""
    residuals = np.asarray(errors, dtype=float)
    residuals = residuals[np.isfinite(residuals)]
    if residuals.size == 0:
        raise ValueError("At least one finite porosity residual is required.")
    return {
        "count": int(residuals.size),
        "mae": float(np.mean(np.abs(residuals))),
        "rmse": float(np.sqrt(np.mean(residuals ** 2))),
        "bias": float(np.mean(residuals)),
        "residual_scatter": float(np.std(residuals, ddof=0)),
        "median_absolute_error": float(np.median(np.abs(residuals))),
    }


def print_residual_performance(
        measurements: Sequence[OpticalMeasurement],
        estimates: Sequence[PorosityEstimate],
) -> None:
    """Print Bruggeman accuracy against gravimetric porosity for porous samples."""
    porous_errors = [
        estimate.porosity_error
        for measurement, estimate in zip(measurements, estimates)
        if not measurement.is_solid_measurement
    ]
    metrics = residual_performance(porous_errors)
    percentage_points = 100.0
    print("\nBruggeman porosity performance against gravimetric porosity")
    print(f"  Porous samples: N = {metrics['count']}")
    print(
        "  Mean absolute error: "
        f"{percentage_points * metrics['mae']:.2f} percentage points"
    )
    print(
        "  Root-mean-square error: "
        f"{percentage_points * metrics['rmse']:.2f} percentage points"
    )
    print(
        "  Mean signed bias: "
        f"{percentage_points * metrics['bias']:+.2f} percentage points "
        "(estimated - gravimetric)"
    )
    print(
        "  Scatter after removing mean bias: "
        f"{percentage_points * metrics['residual_scatter']:.2f} percentage points"
    )
    print(
        "  Median absolute error: "
        f"{percentage_points * metrics['median_absolute_error']:.2f} percentage points"
    )
    print("  These are empirical model-plus-measurement errors, not propagated 1-sigma uncertainties.")


def main() -> None:
    """Run porosity analysis, write tables, save the summary, and print metrics."""
    args = parse_args()
    config_paths = collect_config_paths(args.config_dir.resolve(), args.config)
    if not config_paths:
        raise FileNotFoundError("No campaign config files found.")

    campaigns = [load_campaign_config(path) for path in config_paths]
    args.output_dir.mkdir(parents=True, exist_ok=True)

    measurements = collect_measurements(campaigns)
    assign_gravimetric_porosity(measurements)
    epsilon_ice = tao_ice_refractive_index_at_1thz() ** 2

    estimates_by_model: Dict[str, List[PorosityEstimate]] = {model: [] for model in EMT_MODELS}
    for measurement in measurements:
        for model in EMT_MODELS:
            estimates_by_model[model].append(estimate_porosity(measurement, model, epsilon_ice))

    figures = [
        plot_summary_figure(
            measurements,
            SOLID_ICE_DENSITY_G_CM3,
            estimates_by_model["bruggeman"],
            args.output_dir / "emt_bruggeman_summary",
        ),
    ]
    write_measurement_summary(
        measurements,
        estimates_by_model,
        args.output_dir / "emt_porosity_measurements.csv",
    )
    write_model_metrics(
        estimates_by_model,
        args.output_dir / "emt_porosity_model_metrics.csv",
    )
    print_residual_performance(
        measurements,
        estimates_by_model["bruggeman"],
    )

    if args.show:
        plt.show()
    else:
        for figure in figures:
            plt.close(figure)


params = {"ytick.color":
              "black",

          "xtick.color":
              "black",

          "axes.labelcolor":
              "black",

          "axes.edgecolor":
              "black",

          "mathtext.fontset":
              "cm",

          "mathtext.rm":
              "Times New Roman",

          "font.family":
              "Helvetica Neue",

          "font.size":
              18}

plt.rcParams.update(params)

if __name__ == "__main__":
    main()
